//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ADGBravoImport.SAPService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZBARCODE", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZBARCODE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZFM_INT_BARCODE_INPUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZBARCODE() {
            this.Url = global::ADGBravoImport.Properties.Settings.Default.ADGBravoImport_SAPService_ZBARCODE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZFM_INT_BARCODE_INPUTCompletedEventHandler ZFM_INT_BARCODE_INPUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZBARCODE_INPUT:ZFM_INT_BARCODE_INPUTReques" +
            "t", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZFM_INT_BARCODE_INPUTResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZFM_INT_BARCODE_INPUTResponse ZFM_INT_BARCODE_INPUT([System.Xml.Serialization.XmlElementAttribute("ZFM_INT_BARCODE_INPUT", Namespace="urn:sap-com:document:sap:rfc:functions")] ZFM_INT_BARCODE_INPUT ZFM_INT_BARCODE_INPUT1) {
            object[] results = this.Invoke("ZFM_INT_BARCODE_INPUT", new object[] {
                        ZFM_INT_BARCODE_INPUT1});
            return ((ZFM_INT_BARCODE_INPUTResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZFM_INT_BARCODE_INPUTAsync(ZFM_INT_BARCODE_INPUT ZFM_INT_BARCODE_INPUT1) {
            this.ZFM_INT_BARCODE_INPUTAsync(ZFM_INT_BARCODE_INPUT1, null);
        }
        
        /// <remarks/>
        public void ZFM_INT_BARCODE_INPUTAsync(ZFM_INT_BARCODE_INPUT ZFM_INT_BARCODE_INPUT1, object userState) {
            if ((this.ZFM_INT_BARCODE_INPUTOperationCompleted == null)) {
                this.ZFM_INT_BARCODE_INPUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZFM_INT_BARCODE_INPUTOperationCompleted);
            }
            this.InvokeAsync("ZFM_INT_BARCODE_INPUT", new object[] {
                        ZFM_INT_BARCODE_INPUT1}, this.ZFM_INT_BARCODE_INPUTOperationCompleted, userState);
        }
        
        private void OnZFM_INT_BARCODE_INPUTOperationCompleted(object arg) {
            if ((this.ZFM_INT_BARCODE_INPUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZFM_INT_BARCODE_INPUTCompleted(this, new ZFM_INT_BARCODE_INPUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_INT_BARCODE_INPUT {
        
        private string i_BARCODEField;
        
        private int i_COUNTField;
        
        private bool i_COUNTFieldSpecified;
        
        private string i_DATEField;
        
        private string i_DOCUMENTField;
        
        private string i_ITYPEField;
        
        private string i_TIMEField;
        
        private string i_USERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_BARCODE {
            get {
                return this.i_BARCODEField;
            }
            set {
                this.i_BARCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int I_COUNT {
            get {
                return this.i_COUNTField;
            }
            set {
                this.i_COUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool I_COUNTSpecified {
            get {
                return this.i_COUNTFieldSpecified;
            }
            set {
                this.i_COUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_DATE {
            get {
                return this.i_DATEField;
            }
            set {
                this.i_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_DOCUMENT {
            get {
                return this.i_DOCUMENTField;
            }
            set {
                this.i_DOCUMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_ITYPE {
            get {
                return this.i_ITYPEField;
            }
            set {
                this.i_ITYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_TIME {
            get {
                return this.i_TIMEField;
            }
            set {
                this.i_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_USER {
            get {
                return this.i_USERField;
            }
            set {
                this.i_USERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_INT_BARCODE_INPUTResponse {
        
        private string e_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E_STATUS {
            get {
                return this.e_STATUSField;
            }
            set {
                this.e_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ZFM_INT_BARCODE_INPUTCompletedEventHandler(object sender, ZFM_INT_BARCODE_INPUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZFM_INT_BARCODE_INPUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZFM_INT_BARCODE_INPUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZFM_INT_BARCODE_INPUTResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZFM_INT_BARCODE_INPUTResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591