//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ADGBravoImport.Ser_GH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZSD_TTCVT", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZSD_TTCVT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZfmSdTtcvtOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZSD_TTCVT() {
            this.Url = global::ADGBravoImport.Properties.Settings.Default.ADGBravoImport_Ser_GH_ZSD_TTCVT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZfmSdTtcvtCompletedEventHandler ZfmSdTtcvtCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZSD_TTCVT:ZfmSdTtcvtRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZfmSdTtcvtResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZfmSdTtcvtResponse ZfmSdTtcvt([System.Xml.Serialization.XmlElementAttribute("ZfmSdTtcvt", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZfmSdTtcvt ZfmSdTtcvt1) {
            object[] results = this.Invoke("ZfmSdTtcvt", new object[] {
                        ZfmSdTtcvt1});
            return ((ZfmSdTtcvtResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZfmSdTtcvtAsync(ZfmSdTtcvt ZfmSdTtcvt1) {
            this.ZfmSdTtcvtAsync(ZfmSdTtcvt1, null);
        }
        
        /// <remarks/>
        public void ZfmSdTtcvtAsync(ZfmSdTtcvt ZfmSdTtcvt1, object userState) {
            if ((this.ZfmSdTtcvtOperationCompleted == null)) {
                this.ZfmSdTtcvtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZfmSdTtcvtOperationCompleted);
            }
            this.InvokeAsync("ZfmSdTtcvt", new object[] {
                        ZfmSdTtcvt1}, this.ZfmSdTtcvtOperationCompleted, userState);
        }
        
        private void OnZfmSdTtcvtOperationCompleted(object arg) {
            if ((this.ZfmSdTtcvtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZfmSdTtcvtCompleted(this, new ZfmSdTtcvtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSdTtcvt {
        
        private string iMacvtField;
        
        private string iNgaygiaoField;
        
        private string iTtGiaohangField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMacvt {
            get {
                return this.iMacvtField;
            }
            set {
                this.iMacvtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INgaygiao {
            get {
                return this.iNgaygiaoField;
            }
            set {
                this.iNgaygiaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ITtGiaohang {
            get {
                return this.iTtGiaohangField;
            }
            set {
                this.iTtGiaohangField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstSdTtcvt {
        
        private string spvcField;
        
        private string itemField;
        
        private string maxeField;
        
        private string machuyenField;
        
        private string sttGhField;
        
        private string ctXkField;
        
        private string saleOrderField;
        
        private string saleTypeField;
        
        private string nguoiNhField;
        
        private string diachiGh1Field;
        
        private string diachiGh2Field;
        
        private string ddXnkField;
        
        private string motaXnkField;
        
        private string routerField;
        
        private string routeMotaField;
        
        private string loaiVcField;
        
        private string ngayGhField;
        
        private System.DateTime timeGhField;
        
        private string laiXeField;
        
        private string ttGiaohangField;
        
        private string mathangField;
        
        private string motaMhField;
        
        private decimal luongField;
        
        private string dvtField;
        
        private decimal chieuCaoField;
        
        private decimal chieuRongField;
        
        private decimal dienTichField;
        
        private decimal theTichField;
        
        private string nhomHangField;
        
        private string motaNhField;
        
        private string loaiCuaField;
        
        private byte tlField;
        
        private byte ktField;
        
        private string khungField;
        
        private string rayField;
        
        private string trucKtField;
        
        private decimal soBoField;
        
        private decimal soBo2Field;
        
        private decimal chiphiVcField;
        
        private decimal chiphiLkField;
        
        private string loaitienField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Spvc {
            get {
                return this.spvcField;
            }
            set {
                this.spvcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Maxe {
            get {
                return this.maxeField;
            }
            set {
                this.maxeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Machuyen {
            get {
                return this.machuyenField;
            }
            set {
                this.machuyenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SttGh {
            get {
                return this.sttGhField;
            }
            set {
                this.sttGhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CtXk {
            get {
                return this.ctXkField;
            }
            set {
                this.ctXkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SaleOrder {
            get {
                return this.saleOrderField;
            }
            set {
                this.saleOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SaleType {
            get {
                return this.saleTypeField;
            }
            set {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NguoiNh {
            get {
                return this.nguoiNhField;
            }
            set {
                this.nguoiNhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DiachiGh1 {
            get {
                return this.diachiGh1Field;
            }
            set {
                this.diachiGh1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DiachiGh2 {
            get {
                return this.diachiGh2Field;
            }
            set {
                this.diachiGh2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DdXnk {
            get {
                return this.ddXnkField;
            }
            set {
                this.ddXnkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MotaXnk {
            get {
                return this.motaXnkField;
            }
            set {
                this.motaXnkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Router {
            get {
                return this.routerField;
            }
            set {
                this.routerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RouteMota {
            get {
                return this.routeMotaField;
            }
            set {
                this.routeMotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoaiVc {
            get {
                return this.loaiVcField;
            }
            set {
                this.loaiVcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NgayGh {
            get {
                return this.ngayGhField;
            }
            set {
                this.ngayGhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time")]
        public System.DateTime TimeGh {
            get {
                return this.timeGhField;
            }
            set {
                this.timeGhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaiXe {
            get {
                return this.laiXeField;
            }
            set {
                this.laiXeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TtGiaohang {
            get {
                return this.ttGiaohangField;
            }
            set {
                this.ttGiaohangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mathang {
            get {
                return this.mathangField;
            }
            set {
                this.mathangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MotaMh {
            get {
                return this.motaMhField;
            }
            set {
                this.motaMhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Luong {
            get {
                return this.luongField;
            }
            set {
                this.luongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dvt {
            get {
                return this.dvtField;
            }
            set {
                this.dvtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ChieuCao {
            get {
                return this.chieuCaoField;
            }
            set {
                this.chieuCaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ChieuRong {
            get {
                return this.chieuRongField;
            }
            set {
                this.chieuRongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DienTich {
            get {
                return this.dienTichField;
            }
            set {
                this.dienTichField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TheTich {
            get {
                return this.theTichField;
            }
            set {
                this.theTichField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NhomHang {
            get {
                return this.nhomHangField;
            }
            set {
                this.nhomHangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MotaNh {
            get {
                return this.motaNhField;
            }
            set {
                this.motaNhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoaiCua {
            get {
                return this.loaiCuaField;
            }
            set {
                this.loaiCuaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte Tl {
            get {
                return this.tlField;
            }
            set {
                this.tlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte Kt {
            get {
                return this.ktField;
            }
            set {
                this.ktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Khung {
            get {
                return this.khungField;
            }
            set {
                this.khungField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ray {
            get {
                return this.rayField;
            }
            set {
                this.rayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrucKt {
            get {
                return this.trucKtField;
            }
            set {
                this.trucKtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SoBo {
            get {
                return this.soBoField;
            }
            set {
                this.soBoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SoBo2 {
            get {
                return this.soBo2Field;
            }
            set {
                this.soBo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ChiphiVc {
            get {
                return this.chiphiVcField;
            }
            set {
                this.chiphiVcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ChiphiLk {
            get {
                return this.chiphiLkField;
            }
            set {
                this.chiphiLkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Loaitien {
            get {
                return this.loaitienField;
            }
            set {
                this.loaitienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSdTtcvtResponse {
        
        private string eDesField;
        
        private string eStatusField;
        
        private ZstSdTtcvt[] tbDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EDes {
            get {
                return this.eDesField;
            }
            set {
                this.eDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EStatus {
            get {
                return this.eStatusField;
            }
            set {
                this.eStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstSdTtcvt[] TbData {
            get {
                return this.tbDataField;
            }
            set {
                this.tbDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ZfmSdTtcvtCompletedEventHandler(object sender, ZfmSdTtcvtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZfmSdTtcvtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZfmSdTtcvtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZfmSdTtcvtResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZfmSdTtcvtResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591