//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ADGBravoImport.ADGSAP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'Policy' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZSD_ORDER1", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZSD_ORDER1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZfmSdOrderSerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZSD_ORDER1() {
            this.Url = global::ADGBravoImport.Properties.Settings.Default.ADGBravoImport_ADGSAP_ZSD_ORDER1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZfmSdOrderSerCompletedEventHandler ZfmSdOrderSerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZSD_ORDER1:ZfmSdOrderSerRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZfmSdOrderSerResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZfmSdOrderSerResponse ZfmSdOrderSer([System.Xml.Serialization.XmlElementAttribute("ZfmSdOrderSer", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZfmSdOrderSer ZfmSdOrderSer1) {
            object[] results = this.Invoke("ZfmSdOrderSer", new object[] {
                        ZfmSdOrderSer1});
            return ((ZfmSdOrderSerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZfmSdOrderSerAsync(ZfmSdOrderSer ZfmSdOrderSer1) {
            this.ZfmSdOrderSerAsync(ZfmSdOrderSer1, null);
        }
        
        /// <remarks/>
        public void ZfmSdOrderSerAsync(ZfmSdOrderSer ZfmSdOrderSer1, object userState) {
            if ((this.ZfmSdOrderSerOperationCompleted == null)) {
                this.ZfmSdOrderSerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZfmSdOrderSerOperationCompleted);
            }
            this.InvokeAsync("ZfmSdOrderSer", new object[] {
                        ZfmSdOrderSer1}, this.ZfmSdOrderSerOperationCompleted, userState);
        }
        
        private void OnZfmSdOrderSerOperationCompleted(object arg) {
            if ((this.ZfmSdOrderSerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZfmSdOrderSerCompleted(this, new ZfmSdOrderSerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSdOrderSer {
        
        private string pFdateField;
        
        private string pTdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PFdate {
            get {
                return this.pFdateField;
            }
            set {
                this.pFdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PTdate {
            get {
                return this.pTdateField;
            }
            set {
                this.pTdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstSdItem1 {
        
        private string soCt1Field;
        
        private string idField;
        
        private string ngayCtField;
        
        private string maVtField;
        
        private string tenVtField;
        
        private decimal soluong9Field;
        
        private decimal gia2Field;
        
        private decimal tien2Field;
        
        private decimal tien4Field;
        
        private decimal tongtienField;
        
        private string dvtienField;
        
        private string dvtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SoCt1 {
            get {
                return this.soCt1Field;
            }
            set {
                this.soCt1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NgayCt {
            get {
                return this.ngayCtField;
            }
            set {
                this.ngayCtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaVt {
            get {
                return this.maVtField;
            }
            set {
                this.maVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TenVt {
            get {
                return this.tenVtField;
            }
            set {
                this.tenVtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Soluong9 {
            get {
                return this.soluong9Field;
            }
            set {
                this.soluong9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Gia2 {
            get {
                return this.gia2Field;
            }
            set {
                this.gia2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tien2 {
            get {
                return this.tien2Field;
            }
            set {
                this.tien2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tien4 {
            get {
                return this.tien4Field;
            }
            set {
                this.tien4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tongtien {
            get {
                return this.tongtienField;
            }
            set {
                this.tongtienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dvtien {
            get {
                return this.dvtienField;
            }
            set {
                this.dvtienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dvt {
            get {
                return this.dvtField;
            }
            set {
                this.dvtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZstSdHeader1 {
        
        private string idField;
        
        private string maCtField;
        
        private string ngayCtField;
        
        private string soCtField;
        
        private string maDtField;
        
        private string tenDtField;
        
        private decimal tien2Field;
        
        private decimal tien4Field;
        
        private decimal tongtienField;
        
        private string documentnoField;
        
        private string dvtienField;
        
        private string sxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaCt {
            get {
                return this.maCtField;
            }
            set {
                this.maCtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NgayCt {
            get {
                return this.ngayCtField;
            }
            set {
                this.ngayCtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SoCt {
            get {
                return this.soCtField;
            }
            set {
                this.soCtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaDt {
            get {
                return this.maDtField;
            }
            set {
                this.maDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TenDt {
            get {
                return this.tenDtField;
            }
            set {
                this.tenDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tien2 {
            get {
                return this.tien2Field;
            }
            set {
                this.tien2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tien4 {
            get {
                return this.tien4Field;
            }
            set {
                this.tien4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tongtien {
            get {
                return this.tongtienField;
            }
            set {
                this.tongtienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Documentno {
            get {
                return this.documentnoField;
            }
            set {
                this.documentnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dvtien {
            get {
                return this.dvtienField;
            }
            set {
                this.dvtienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sx {
            get {
                return this.sxField;
            }
            set {
                this.sxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmSdOrderSerResponse {
        
        private string pExtypeField;
        
        private string pMesageField;
        
        private ZstSdHeader1[] tbHeaderField;
        
        private ZstSdItem1[] tbItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PExtype {
            get {
                return this.pExtypeField;
            }
            set {
                this.pExtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PMesage {
            get {
                return this.pMesageField;
            }
            set {
                this.pMesageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstSdHeader1[] TbHeader {
            get {
                return this.tbHeaderField;
            }
            set {
                this.tbHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZstSdItem1[] TbItem {
            get {
                return this.tbItemField;
            }
            set {
                this.tbItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ZfmSdOrderSerCompletedEventHandler(object sender, ZfmSdOrderSerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZfmSdOrderSerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZfmSdOrderSerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZfmSdOrderSerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZfmSdOrderSerResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591